### ISSUE TITLE
500 error

### ISSUE THREAD

**Issue by benshrimpton** [bradyvercher/better-internal-link-search#14]
My local dev version works fine, but deploying it to server I get this:

<img width="1335" alt="screen shot 2017-10-17 at 3 59 19 pm" src="https://user-images.githubusercontent.com/739699/31686473-33bb1fec-b354-11e7-826e-a4ee9fc397ce.png">

**Comment by bradyvercher** [comment]
Hi @benshrimpton, can you access the error log on your server to see what's causing that 500 error?

**Comment by benshrimpton** [comment]
Thanks for your reply, i will take a look.

Ben

**Comment by bradyvercher** [comment]
Closing due to a lack of activity. Please feel free to reopen or start a new issue if this is still a problem.
